jornal_commercio/urls.py
from django.urls import path
from . import views
from jornal_commercio import views

urlpatterns = [
    path('', views.home, name="home"),
    path('salvar-feedback', views.salvar_feedback, name='salvar_feedback'),
    path('noticia/<slug:slug>/', views.detalhe_noticia, name='detalhe_noticia'),
    path('comunidades/', views.ComunidadeListView.as_view(), name='comunidades_lista'),
    path('comunidades/<int:pk>/', views.ComunidadeDetailView.as_view(), name='comunidade_detalhe'),
    path('publicacao/<int:pk>/curtir/', views.curtir_publicacao, name='curtir_publicacao'),
    path('publicacao/<int:pk>/descurtir/', views.descurtir_publicacao, name='descurtir_publicacao'),
    path('publicacao/<int:pk>/salvar/', views.salvar_publicacao, name='salvar_publicacao'),
    path('publicacao/<int:pk>/comentar/', views.adicionar_comentario, name='adicionar_comentario'),
    path('comunidades/<int:pk>/toggle_membro/', views.toggle_membro, name='toggle_membro'),
    path('api/salvar-quiz/', views.salvar_resposta_quiz, name='salvar_resposta_quiz'),
    path('api/finalizar-quiz/<int:quiz_id>/', views.finalizar_quiz, name='finalizar_quiz'),
    path('jc-quest/', views.quiz_hub, name='quiz_hub'),
    path('jc-quest/jogar/<int:quiz_id>/', views.quiz_play, name='quiz_play'),
    path('edicao-do-dia/', views.pagina_edicao_do_dia, name='pagina_edicao'),
    path('api/atualizar-leitura/', views.atualizar_historico_leitura, name='atualizar_historico_leitura'),
    path('anuncio/clique/<int:anuncio_id>/', views.computar_clique_anuncio, name='clique_anuncio'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),
    path('', include('jornal_commercio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import CustomLoginForm 

app_name = 'usuario'

urlpatterns = [
    path('registrar/', views.registrar, name='registrar'),
    
    path('login/', auth_views.LoginView.as_view(
        template_name='usuario/login.html',
        authentication_form=CustomLoginForm
    ), name='login'),

    path('logout/', auth_views.LogoutView.as_view(
        template_name='usuario/logout.html'
    ), name='logout'),
    path('registrar/senha/', views.registrar_senha, name='registrar_senha'),
    path('registrar/frequencia/', views.registrar_frequencia, name='registrar_frequencia'),
    path('registrar/interesses/', views.registrar_interesses, name='registrar_interesses'),
    path('registrar/sucesso/', views.registrar_sucesso, name='registrar_sucesso'),
    path('perfil/', views.perfil, name='perfil'),
    # path('perfil/interesses/', views.interesses, name='interesses'),
    path('perfil/interesses/', views.interesses, name='interesses'),
    path('perfil/privacidade/', views.privacidade, name='privacidade'),
    path('password-reset/', 
         auth_views.PasswordResetView.as_view(
             template_name='usuario/password_reset.html' 
         ), 
         name='password_reset'),
    
    path('newsletter/', 
         views.newsletter_page, 
         name='newsletter_page'),
    
    path('newsletter/inscrever/', 
         views.subscribe_newsletter, 
         name='subscribe_newsletter'),
    
    path('newsletter/cancelar/<uuid:token>/', 
         views.unsubscribe_newsletter, 
         name='unsubscribe_newsletter'),

    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(
             template_name='usuario/password_reset_done.html' 
         ), 
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name='usuario/password_reset_confirm.html'
         ), 
         name='password_reset_confirm'),

    path('password-reset-complete/', 
         auth_views.PasswordResetCompleteView.as_view(
             template_name='usuario/password_reset_complete.html'
         ), 
         name='password_reset_complete'),
]

jornal_commercio/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.dispatch import receiver
import threading

CATEGORIA_CHOICES = [
    ('MUNDO', 'Mundo'),
    ('SEGURANCA_VIARIA', 'Segurança Viária'),
    ('CIDADES', 'Cidades'),
    ('POLITICA', 'Política'),
    ('GERAL', 'Geral'),
    ('EDUCACAO', 'Educação'),
    ('ESPORTE', 'Esporte'),
    ('SAUDE', 'Saúde e Bem-Estar'),
    ('MOBILIDADE', 'Mobilidade'),
    ('CULTURA', 'Cultura'),
    ('ENTRETENIMENTO', 'Entretenimento'),
    ('ECONOMIA', 'Economia'),
    ('COMERCIO', 'Comércio'),
    ('SOCIAL', 'Social'),
]

class Noticia(models.Model):
    titulo = models.CharField(
        max_length=200,
        blank=False,
        null=False,
        verbose_name="Título da notícia"
    )
    
    resumo = models.TextField(
        verbose_name="Resumo (linha fina)",
        help_text="Um breve resumo da notícia que aparecerá na home page.",
        blank=True,
        null=True
    )

    conteudo = models.TextField(
        blank=False,
        null=False,
        verbose_name="Conteúdo da notícia"
    )

    autor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Autor"
    )
    
    categoria = models.CharField(
        max_length=50,
        choices=CATEGORIA_CHOICES,
        default='GERAL',
        verbose_name="Categoria"
    )

    data_publicacao = models.DateTimeField(
        default=timezone.now,
        verbose_name="Data de publicação"
    )

    data_atualizacao = models.DateTimeField(
        auto_now=True,
        verbose_name="Última atualização"
    )

    slug = models.SlugField(
        max_length=255,
        unique=True,
        blank=True,
        null=True,
        help_text="Usado para a URL da notícia. Deixe em branco para gerar automaticamente."
    )

    imagem_principal = models.ImageField(
        upload_to='noticias_imagens/',
        blank=True,
        null=True,
        verbose_name="Imagem Principal"
    )

    class Meta:
        ordering = ['-data_publicacao']

    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        try:
            return reverse('jornal_commercio:noticia_detalhe', kwargs={'slug': self.slug})
        except:
            return "/"
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.titulo)
            original_slug = self.slug
            queryset = Noticia.objects.all().filter(slug__iexact=self.slug).exists()
            count = 1
            while queryset:
                self.slug = f"{original_slug}-{count}"
                count += 1
                queryset = Noticia.objects.all().filter(slug__iexact=self.slug).exists()
                
        super(Noticia, self).save(*args, **kwargs)


class Feedback(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True, help_text="Nome (opcional)")
    email = models.EmailField(blank=True, null=True, help_text="E-mail (opcional)")
    mensagem = models.TextField()
    data_envio = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedbacks"
        ordering = ['-data_envio']

    def __str__(self):
        return f"Feedback de {self.nome or 'Anônimo'} em {self.data_envio.strftime('%d/%m/%Y')}"

class Comunidade(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    descricao = models.TextField(blank=True, null=True)
    
    categoria = models.CharField(
        max_length=50,
        choices=CATEGORIA_CHOICES,
        default='GERAL',
        verbose_name="Categoria",
        unique=True
    )

    criador = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL,
        null=True, 
        related_name="comunidades_criadas"
    )
    
    membros = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="comunidades_seguidas",
        blank=True
    )
    
    imagem_banner = models.ImageField(upload_to='banners_comunidade/', blank=True, null=True)
    imagem_card = models.ImageField(upload_to='cards_comunidade/', blank=True, null=True)
    
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name = "Comunidade"
        verbose_name_plural = "Comunidades"


class Publicacao(models.Model):
    comunidade = models.ForeignKey(
        Comunidade, 
        on_delete=models.CASCADE,
        related_name="publicacoes"
    )
    
    autor = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name="publicacoes"
    )
    
    conteudo = models.TextField()
    data_publicacao = models.DateTimeField(auto_now_add=True)
    
    is_destaque = models.BooleanField(default=False)

    curtidas = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="publicacoes_curtidas",
        blank=True
    )

    descurtidas = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="publicacoes_descurtidas",
        blank=True
    )
    
    salvo_por = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="publicacoes_salvas",
        blank=True
    )
    
    noticia_relacionada = models.ForeignKey(
        Noticia,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="publicacoes_comunidade",
        verbose_name="Notícia Relacionada"
    )
    
    class Meta:
        ordering = ['-data_publicacao']
        verbose_name = "Publicação"
        verbose_name_plural = "Publicações"

    def __str__(self):
        return f"Post de {self.autor.username} em {self.comunidade.nome}"


class Comentario(models.Model):
    publicacao = models.ForeignKey(
        Publicacao, 
        on_delete=models.CASCADE,
        related_name="comentarios"
    )
    
    autor = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name="comentarios"
    )
    
    conteudo = models.TextField()
    data_publicacao = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['data_publicacao']
        verbose_name = "Comentário"
        verbose_name_plural = "Comentários"

    def __str__(self):
        return f"Comentário de {self.autor.username} em {self.publicacao.id}"
    

class HistoricoLeitura(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name="historico_leitura"
    )
    
    noticia = models.ForeignKey(
        Noticia, 
        on_delete=models.CASCADE,
        related_name="leituras"
    )
    
    porcentagem_lida = models.PositiveIntegerField(
        default=0, 
        verbose_name="Porcentagem Lida"
    )
    
    lido_completo = models.BooleanField(default=False, verbose_name="Leitura Concluída")

    ultima_interacao = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name = "Histórico de Leitura"
        verbose_name_plural = "Históricos de Leitura"
        unique_together = ('usuario', 'noticia')
        ordering = ['-ultima_interacao'] 

    def __str__(self):
        return f"{self.usuario} - {self.noticia} ({self.porcentagem_lida}%)"

    def save(self, *args, **kwargs):
        if self.porcentagem_lida >= 100:
            self.porcentagem_lida = 100
            self.lido_completo = True
        super(HistoricoLeitura, self).save(*args, **kwargs)

class Quiz(models.Model):
    noticia = models.OneToOneField(
        Noticia,
        on_delete=models.CASCADE,
        related_name='quiz',
        verbose_name="Notícia Relacionada"
    )
    titulo = models.CharField(max_length=200, verbose_name="Título do Quiz", blank=True)
    descricao = models.TextField(blank=True, verbose_name="Descrição/Instruções")
    
    gerado_por_ia = models.BooleanField(default=False, verbose_name="Gerado automaticamente?")
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Quiz: {self.noticia.titulo}"

    class Meta:
        verbose_name = "Quiz"
        verbose_name_plural = "Quizzes"


class Pergunta(models.Model):
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='perguntas'
    )
    texto = models.TextField(verbose_name="Enunciado da Pergunta")
    ordem = models.PositiveIntegerField(default=0, help_text="Ordem de exibição")

    def __str__(self):
        return f"{self.quiz.noticia.titulo[:20]}... - {self.texto[:50]}"
    
    class Meta:
        ordering = ['ordem']


class Opcao(models.Model):
    pergunta = models.ForeignKey(
        Pergunta,
        on_delete=models.CASCADE,
        related_name='opcoes'
    )
    texto = models.CharField(max_length=255, verbose_name="Texto da Opção")
    correta = models.BooleanField(default=False, verbose_name="É a resposta correta?")

    def __str__(self):
        return f"({'X' if self.correta else ' '}) {self.texto}"

class TentativaQuiz(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='tentativas_quiz'
    )
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='tentativas'
    )
    data_inicio = models.DateTimeField(auto_now_add=True)
    data_conclusao = models.DateTimeField(null=True, blank=True)
    
    pontuacao = models.PositiveIntegerField(default=0, verbose_name="Acertos")
    
    concluido = models.BooleanField(default=False)

    def calcular_e_salvar_pontuacao(self):
        """
        Calcula o total de acertos baseados nas respostas do usuário

jornal_commercio/forms.py
from django import forms
from .models import Feedback, Publicacao, Comentario

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'

class PublicacaoForm(forms.ModelForm):
    class Meta:
        model = Publicacao
        
        # O usuário só precisa digitar o 'conteudo'.
        # 'autor' e 'comunidade' serão definidos na view.
        fields = ['conteudo'] 
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Adiciona um placeholder e remove o "label"
        self.fields['conteudo'].widget.attrs.update({
            'placeholder': 'Escreva sua publicação...',
            'rows': 3 # Deixa a caixa de texto menor
        })
        self.fields['conteudo'].label = False

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        
        # O usuário só precisa digitar o 'conteudo'.
        # 'autor' e 'publicacao' serão definidos na view.
        fields = ['conteudo'] 
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Adiciona um placeholder e remove o "label"
        self.fields['conteudo'].widget.attrs.update({
            'placeholder': 'Escreva seu comentário...',
            'rows': 2 # Caixa de texto com 2 linhas
        })
        self.fields['conteudo'].label = False

jornal_commercio/templates/jornal_commercio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Jornal do Commercio{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'jornal_commercio/css/style.css' %}">
    
    {% block styles %}{% endblock %}
</head>
<body> <header class="top-header">
    <div class="container">
        <nav class="top-nav-left">
            <ul>
                <li><a href="#">EDIÇÃO </a></li>
                <li><a href="#">ASSUNTOS</a></li>
            </ul>
        </nav>
        <div class="logo-container">
            <a href="/">
                <img src="{% static 'jornal_commercio/images/logo_jc.png' %}" alt="Logo JC" height="35">
            </a>
        </div>
        <div class="header-icons">
        
        <a href="#" id="open-feedback-btn" aria-label="Notificações">
            <img src="{% static 'jornal_commercio/images/notification.png' %}" alt="Notificações">
        </a>
        
        <a href="#" aria-label="Buscar">
            <img src="{% static 'jornal_commercio/images/search.png' %}" alt="Buscar">
        </a>
        <a href="#" aria-label="Perfil de Usuário">
            <img src="{% static 'jornal_commercio/images/user.png' %}" alt="Usuário">
        </a>    
    </div>
    </div>
    </header>

    <nav class="main-nav">
        <div class="container">
            <ul>
                <li><a href="#">NOTÍCIAS DO DIA</a></li>
                <li><a href="#">COLUNISTAS</a></li>
                <li><a href="#">NOTÍCIAS DE PE</a></li>
                <li><a href="#">COMUNIDADES</a></li>
                <li><a href="#">RECALL DA MARCA</a></li>
                <li><a href="#">ANUNCIE AQUI</a></li>
            </ul>
        </div>
    </nav>

    {% if messages %}
        <div class="container messages-container">
            {% for message in messages %}
                <div class="message {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    <main>
        {% block content %}
        {% endblock content %}
    </main>

{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Jornal do Commercio{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'jornal_commercio/css/style.css' %}">

    {% block styles %}{% endblock %}
</head>
<body> <header class="top-header">
    <div class="container">
        <nav class="top-nav-left">
            <ul>
                <li><a href="#">EDIÇÃO </a></li>
                <li><a href="#">ASSUNTOS</a></li>
            </ul>
        </nav>
        <div class="logo-container">
            <a href="/">
                <img src="{% static 'jornal_commercio/images/logo_jc.png' %}" alt="Logo JC" height="35">
            </a>
        </div>
        <div class="header-icons">
        
        <a href="#" id="open-feedback-btn" aria-label="Notificações">
            <img src="{% static 'jornal_commercio/images/notification.png' %}" alt="Notificações">
        </a>
        
        <a href="#" aria-label="Buscar">
            <img src="{% static 'jornal_commercio/images/search.png' %}" alt="Buscar">
        </a>
        <a href="#" aria-label="Perfil de Usuário">
            <img src="{% static 'jornal_commercio/images/user.png' %}" alt="Usuário">
        </a>    
    </div>
    </div>
    </header>

    <nav class="main-nav">
        <div class="container">
            <ul>
                <li><a href="#">NOTÍCIAS DO DIA</a></li>
                <li><a href="#">COLUNISTAS</a></li>
                <li><a href="#">NOTÍCIAS DE PE</a></li>
                <li><a href="#">COMUNIDADES</a></li>
                <li><a href="#">RECALL DA MARCA</a></li>
                <li><a href="#">ANUNCIE AQUI</a></li>
            </ul>
        </div>
    </nav>

    {% if messages %}
        <div class="container messages-container">
            {% for message in messages %}
                <div class="message {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <footer class="site-footer">
        <div class="container">
            <div class="footer-column">
                <img src="{% static 'jornal_commercio/images/logo_jc.png' %}" alt="Logo JC" class="footer-logo" height="40">
                <a href="{% url 'usuario:newsletter_page' %}">Newsletter</a>
                <a href="#">Quem somos nós</a>
                <a href="#">FAQ</a>
            </div>
            <div class="footer-column">
                <h4>OUÇA AGORA</h4>
                <a href="#">Rádio Jornal</a>
                <a href="#">TV Jornal</a>
            </div>
            <div class="footer-column">
                <h4>SIGA O JC</h4>
                <div class="social-icons">
                     <a href="https://www.youtube.com/c/TVJCPE/videos" aria-label="YouTube">
                         <img src="{% static 'jornal_commercio/images/youtube.png' %}" alt="Buscar">
                     </a>
                     <a href="https://www.instagram.com/jc_pe/?hl=pt" aria-label="Instagram">
                         <img src="{% static 'jornal_commercio/images/instagram.png' %}" alt="Buscar">
                     </a>
                     <a href="https://x.com/jc_pe" aria-label="X/Twitter">
                         <img src="{% static 'jornal_commercio/images/twitter.png' %}" alt="Buscar">
                     </a>
                </div>
            </div>
        </div>
    </footer>


</body>
    <footer class="site-footer">
        <div class="container">
            <div class="footer-column">
                <img src="{% static 'jornal_commercio/images/logo_jc.png' %}" alt="Logo JC" class="footer-logo" height="40">
                <a href="{% url 'usuario:newsletter_page' %}">Newsletter</a>
                <a href="#">Quem somos nós</a>
                <a href="#">FAQ</a>
            </div>
            <div class="footer-column">
                <h4>OUÇA AGORA</h4>
                <a href="#">Rádio Jornal</a>
                <a href="#">TV Jornal</a>
            </div>
            <div class="footer-column">
                <h4>SIGA O JC</h4>
                <div class="social-icons">
                     <a href="https://www.youtube.com/c/TVJCPE/videos" aria-label="YouTube">
                         <img src="{% static 'jornal_commercio/images/youtube.png' %}" alt="Buscar">
                     </a>
                     <a href="https://www.instagram.com/jc_pe/?hl=pt" aria-label="Instagram">
                         <img src="{% static 'jornal_commercio/images/instagram.png' %}" alt="Buscar">
                     </a>
                     <a href="https://x.com/jc_pe" aria-label="X/Twitter">
                         <img src="{% static 'jornal_commercio/images/twitter.png' %}" alt="Buscar">
                     </a>
                </div>
            </div>
        </div>
    </footer>


</body>
</html>

jornal_commercio/templates/jornal_commercio/comunidades_lista.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}Comunidades - Jornal Commercio{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'jornal_commercio/css/comunidades_lista.css' %}">
{% endblock %}

{% block content %}
<div class="container-principal-comunidades">

    <header class="comunidades-cabecalho">
        <h2>Comunidades</h2>
        
        <div class="comunidades-filtros">
            <form class="filtro-busca" method="GET" action="{% url 'comunidades_lista' %}">
                <input type="text" name="q" placeholder="Busca" value="{{ search_query }}">
                {% if filtro_ativo != 'alta' %}
                    <input type="hidden" name="filtro" value="{{ filtro_ativo }}">
                {% endif %}
            </form>

            <nav class="filtro-abas">
                <a href="?filtro=alta{% if search_query %}&q={{ search_query }}{% endif %}" class="aba-item {% if filtro_ativo == 'alta' %}aba-ativa{% endif %}">Em Alta</a>
                <a href="?filtro=seguindo{% if search_query %}&q={{ search_query }}{% endif %}" class="aba-item {% if filtro_ativo == 'seguindo' %}aba-ativa{% endif %}">Seguindo</a>
                <a href="?filtro=criados{% if search_query %}&q={{ search_query }}{% endif %}" class="aba-item {% if filtro_ativo == 'criados' %}aba-ativa{% endif %}">Criados por usuários</a>
            </nav>
            
            <button class="filtro-btn">Filtros</button>
        </div>
    </header>

    <div class="comunidade-grid">

        {% for comunidade in comunidades %}
            <a href="{% url 'comunidade_detalhe' pk=comunidade.pk %}" class="comunidade-card">
                
                <div class="card-imagem">
                    {% if comunidade.imagem_card %}
                        <img src="{{ comunidade.imagem_card.url }}" alt="Imagem da comunidade {{ comunidade.nome }}">
                    {% else %}
                        <div class="card-imagem-placeholder">Sem Imagem</div>
                    {% endif %}
                </div>
                
                <div class="card-conteudo">
                    <h3>{{ comunidade.nome }}</h3>
                    
                    <div class="card-info">
                        <span class="info-avatar"></span>
                        <span class="info-autor">{{ comunidade.criador.username }}</span>
                        <span class="info-stats">
                            {{ comunidade.membros.count }}
                        </span>
                    </div>
                </div>
            </a>
        {% empty %}
            {% if search_query %}
                <p>Nenhum resultado encontrado para "{{ search_query }}".</p>
            {% else %}
                <p>Nenhuma comunidade encontrada para este filtro.</p>
            {% endif %}
        {% endfor %}

    </div>

    <div class="paginacao">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}{% if filtro_ativo != 'alta' %}&filtro={{ filtro_ativo }}{% endif %}">Anterior</a>
        {% endif %}

        <span class="pagina-atual">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if search_query %}&q={{ search_query }}{% endif %}{% if filtro_ativo != 'alta' %}&filtro={{ filtro_ativo }}{% endif %}">Próxima</a>
        {% endif %}
    </div>

</div>
{% endblock %}